#!/usr/bin/env python3
"""Read template.html, replace placeholders with today's content, write to index.html."""

import re

replacements = {
    "{{DATE}}": "Friday, 19 June 2026",

    # Weather — Carrum Downs VIC, 5-day from Fri 19 Jun
    # BOM pattern: showers easing through weekend; winter solstice Sunday; partly cloudy next week
    "{{WEATHER_1}}": "FRI 19 · 🌧 Showers · 16°C",
    "{{WEATHER_2}}": "SAT 20 · 🌦 Shower risk · 15°C",
    "{{WEATHER_2_CLASS}}": "rain",
    "{{WEATHER_3}}": "SUN 21 · ⛅ Clearing · 15°C",
    "{{WEATHER_3_CLASS}}": "",
    "{{WEATHER_4}}": "MON 22 · 🌥 Mostly cloudy · 15°C",
    "{{WEATHER_5}}": "TUE 23 · ⛅ Partly cloudy · 15°C",
    "{{WEATHER_ALERT}}": "⚠ SHOWERS CLEARING THROUGH WEEKEND · WINTER SOLSTICE SUNDAY 21 JUN",

    # World
    "{{WORLD_1_FLAG}}": "🌐 Gaza · Middle East",
    "{{WORLD_1_HEADLINE}}": "Israeli Strikes Kill Three in Gaza City — Operations Continue Despite October Ceasefire, Toll Now 1,005",
    "{{WORLD_1_SUMMARY}}": "Israeli drone strikes killed at least three Palestinians in the Gaza City area on June 18, with the cumulative toll since October's ceasefire agreement reaching 1,005 deaths according to Gaza health officials. UN Secretary-General António Guterres called for full ceasefire compliance; Israel says operations target active Hamas military infrastructure. The continued conflict has drawn sharp international criticism and complicated the diplomatic momentum generated by the US-Iran deal signed in Zurich on Thursday.",
    "{{WORLD_1_URL}}": "https://www.aljazeera.com/news/2026/6/18/israel-kills-at-least-three-palestinians-in-gaza-city-drone-strike",

    "{{WORLD_2_FLAG}}": "🌐 US · Long Island",
    "{{WORLD_2_HEADLINE}}": "Gilgo Beach Killer Rex Heuermann Sentenced to Multiple Life Terms — DNA Genealogy Cracked a Decade-Long Cold Case",
    "{{WORLD_2_SUMMARY}}": "Rex Heuermann, the Long Island architect who murdered eight women over more than a decade along the Gilgo Beach coastline, was sentenced today to multiple consecutive life terms with no possibility of parole. Victims' families called him a 'demon in human clothing' in powerful courtroom impact statements. The case was cracked in 2023 via genealogical DNA analysis — a technique now transforming cold-case investigations globally. The sentencing closes a chapter that changed how law enforcement worldwide applies DNA genealogy to unidentified remains.",
    "{{WORLD_2_URL}}": "https://www.nbcnews.com/news/us-news/rex-heuermann-sentenced-long-islands-gilgo-beach-serial-murders-pleadi-rcna349811",

    # Economics
    "{{ECON_1_FLAG}}": "💰 ATO · Super Reform",
    "{{ECON_1_HEADLINE}}": "Payday Super Starts 1 July — 11 Days to Prepare Your Payroll Before the ATO Clearing House Closes for Good",
    "{{ECON_1_SUMMARY}}": "From 1 July 2026, employers must pay superannuation within seven business days of every payday rather than quarterly — the most significant change to the super system since its 1992 introduction. At the same time, the ATO's Small Business Super Clearing House closes permanently on 1 July. Any business still using it must register with an alternative clearing house before June 30. Outstanding quarterly super payments must reach employees' super funds — not just your bank account — before June 30 to count this financial year. Payroll software needs to be updated and confirmed compliant before the changeover.",
    "{{ECON_1_URL}}": "https://4front.net.au/business-consulting/super-update-eofy-payment-deadlines-payday-super-changes-from-1-july-2026/",

    "{{ECON_2_FLAG}}": "📊 Inflation · Australia",
    "{{ECON_2_HEADLINE}}": "Australian Inflation Holds at 4.6% as Electricity, Groceries, Fuel and Insurance All Rise Simultaneously",
    "{{ECON_2_SUMMARY}}": "New analysis finds Australian inflation sitting at 4.6% — well above the RBA's 2–3% target — with the unusual pattern of multiple essential business expenses rising at once: electricity, groceries, fuel, insurance and wages all increasing in the same period. For a trades business, every major operating cost is moving up simultaneously heading into the new financial year. The July 1 cost hit — fuel excise reversal, payday super, and minimum wage increase — layers on top of an already pressured cost base. This is the final 11 days to lock in pricing before July costs become the new normal.",

    # Tech / AI
    "{{TECH_1_FLAG}}": "🤖 OpenAI · Agentic AI",
    "{{TECH_1_HEADLINE}}": "OpenAI Tops $25 Billion in Annualised Revenue as AI Shifts From Chat to Autonomous Task Completion",
    "{{TECH_1_SUMMARY}}": "OpenAI has surpassed $25 billion in annualised revenue and is taking early steps toward a public listing, potentially in late 2026 — with rival Anthropic approaching $19 billion. The trend driving both companies' growth is the shift from conversational AI to 'agentic' AI: systems that complete multi-step tasks autonomously rather than just answering questions. For trades businesses, this shift means AI is moving beyond drafting quotes and emails toward managing follow-up sequences, supplier communications, scheduling and invoice chasing end-to-end — without prompting.",
    "{{TECH_1_URL}}": "https://theaitrack.com/ai-news-june-2026-in-depth-and-concise/",

    "{{TECH_2_FLAG}}": "🤖 NVIDIA · SK Hynix",
    "{{TECH_2_HEADLINE}}": "NVIDIA and SK Hynix Sign Multiyear Deal to Co-Develop Next-Generation AI Memory — Signals Where AI Hardware Heads Through 2028",
    "{{TECH_2_SUMMARY}}": "NVIDIA and South Korea's SK hynix have announced a multiyear technology partnership to co-develop next-generation memory aligned with NVIDIA's AI infrastructure roadmap. Memory bandwidth and capacity are currently the primary bottleneck limiting how powerful AI models can run. The deal locks in the hardware path for NVIDIA's next GPU generations. For businesses using AI tools: AI model capability will continue scaling rapidly through 2026–28, meaning the tools available today will look modest in two to three years. Build the habit now, while the cost is low and the learning curve is short.",

    # Robotics
    "{{ROBOT_1_FLAG}}": "🦾 ABB · Physical AI",
    "{{ROBOT_1_HEADLINE}}": "ABB Robotics Launches Physical AI Toolchain — Industrial Robots Can Now Train on Simulated Data, Not Just Real-World Examples",
    "{{ROBOT_1_SUMMARY}}": "ABB Robotics has unveiled its Physical AI Toolchain, debuting at Automate 2026 in Chicago next week (June 22–25, North America's largest automation show). The toolchain enables industrial robots to be trained on simulated and synthetic data rather than requiring extensive real-world footage, dramatically cutting deployment time and cost. A single software stack now spans data generation, training, validation and live deployment. The practical implication: complex processes that were too variable or hazardous to automate previously — including coating, surface preparation and industrial inspection — become candidates for AI-powered robotics as training no longer requires putting a robot in the actual environment to learn from scratch.",
    "{{ROBOT_1_URL}}": "https://www.roboticstomorrow.com/news/2026/06/17/abb-robotics-delivers-new-industry-ready-physical-ai-at-automate-2026/26735/",

    # Australia
    "{{AUS_1_HEADLINE}}": "Lincraft Closes All 28 Physical Stores After 88 Years — 300 Jobs Gone as Retailer Goes Online-Only",
    "{{AUS_1_SUMMARY}}": "Australian fabric and craft chain Lincraft has confirmed all remaining physical stores across Australia and New Zealand will close progressively over coming months, with over 300 staff affected. The 88-year-old retailer cited prolonged challenging retail conditions, rising operating costs and competition from low-cost international online operators. The exit follows a string of major Australian retail closures in 2025–26 driven by the same cost and consumer-behaviour pressures now reshaping trades suppliers and building product retailers.",
    "{{AUS_1_URL}}": "https://www.nzherald.co.nz/business/lincraft-shutting-physical-stores-as-retailer-moves-fully-online-300-jobs-affected/HFJRZSRTSVCB7C65BGMLERRB6U/",

    "{{AUS_2_HEADLINE}}": "Socceroos Face USA Tonight in Seattle — Both Teams Top Group D, First-Ever World Cup Meeting",
    "{{AUS_2_SUMMARY}}": "Australia takes on the United States tonight at Lumen Field, Seattle (kickoff 3pm ET Friday / 5am AEST Saturday) in the most important Socceroos match in years. Both teams sit atop Group D on three points — the Socceroos beat Turkey 2-0, the USA defeated Paraguay 4-1. The winner takes commanding control of the group. This is the first-ever World Cup meeting between the two nations. Live on SBS. Federation Square opens at 11pm tonight if you want to watch it with 7,000 other Australians.",

    # Victoria
    "{{VIC_1_HEADLINE}}": "Fed Square Gates Open 11pm Tonight for Socceroos v USA — Up to 7,000 Fans Expected for Pre-Dawn Watch Party",
    "{{VIC_1_SUMMARY}}": "Federation Square opens at 11pm tonight, Friday June 19, for the free pre-dawn screening of Australia v USA (kickoff 5am AEST Saturday). An estimated 7,000 fans attended the opening match screening, creating a festival atmosphere with flags, face paint and chanting. Entry is free and first-come-first-served. Three entry gates open 60 minutes before kickoff; if Fed Square reaches capacity, overflow is directed to AAMI Park. Bag checks in place. It will be a cold Melbourne winter night — dress accordingly.",

    # Science
    "{{SCI_1_FLAG}}": "🔬 Nephrology · JCI",
    "{{SCI_1_HEADLINE}}": "Mayo Clinic Discovers a Hidden Backup System in the Kidneys That Nobody Knew Existed",
    "{{SCI_1_SUMMARY}}": "Scientists at Mayo Clinic have uncovered a previously unknown mechanism by which the kidneys regulate the body's water balance — one that operates entirely independently of antidiuretic hormone (ADH), the signal long believed to solely govern the process. The discovery emerged accidentally: researchers testing the old drug probenecid on polycystic kidney disease (PKD) expected it to worsen cyst growth but found it instead slowed it, revealing the hidden pathway. Led by nephrologist Dr Fouad Chebib, the study was published in the Journal of Clinical Investigation on June 17. The finding overturns fundamental assumptions held for decades about kidney physiology and opens new treatment pathways for PKD, which affects an estimated 600,000 Australians.",

    # Business Insight
    "{{INSIGHT_TITLE}}": "The Payroll Change Nobody Is Talking About — Payday Super Starts July 1 and It Changes Your Cash Flow Permanently",
    "{{INSIGHT_BODY}}": "For 34 years, Australian employers have paid superannuation quarterly — a known, manageable lump sum four times a year. From 1 July 2026, that changes permanently. Under the new Payday Super rules, super must be paid within seven business days of every single pay run. For a trades business paying staff weekly, super is now a weekly cash flow item. For fortnightly payroll, it is fortnightly. Quarterly budgeting for super is over. The immediate practical steps: first, check whether your payroll software — Xero, MYOB, Employment Hero, or similar — is Payday Super compliant. Most providers have been rolling out updates, but you need to confirm yours is live, not planned. Second, if you currently use the ATO's Small Business Super Clearing House, stop: it closes permanently on 1 July. Register with an alternative clearing house — Beam, QuickSuper, or your super fund's own portal — before June 30. Third, make sure your final quarterly super payment for this financial year reaches employees' funds before June 30 if you want to claim the deduction this year. The businesses that handle this quietly are the ones whose payroll software is already set up. The ones who find out in July are the ones who cop late-payment penalties from day one of the new financial year. Eleven days. Check the payroll software today.",

    # Fun Facts
    "{{FACT_1}}": "Lumen Field in Seattle — venue for tonight's Socceroos v USA World Cup clash — holds the Guinness World Record for the loudest crowd roar at a professional sporting event, clocking 137.6 decibels during a 2013 Seattle Seahawks NFL game. The stadium's famous noise levels earned Seattle fans the nickname 'the 12s,' representing a notional twelfth player on the field. Australia will be playing in one of the most hostile home-crowd environments in North American sport.",

    "{{FACT_2}}": "Australia's compulsory superannuation system turns 34 years old on 1 July 2026. Introduced by the Keating Government in 1992 at a 3% contribution rate, the Super Guarantee reaches its legislated ceiling of 12% on 1 July 2026. The system has accumulated over $3.9 trillion in assets — making Australia the fourth-largest pension pool on Earth and larger than the country's entire annual GDP.",

    "{{FACT_3}}": "The FIFA World Cup Trophy, introduced in 1974 after the original Jules Rimet Trophy was permanently stolen in Brazil in 1983, is crafted from solid 18-carat gold with a malachite base and weighs 6.175 kilograms. Under FIFA rules, no winning nation may ever permanently keep the original — each receives a gold-plated replica. It was designed by Italian sculptor Silvio Gazzaniga. The Jules Rimet was famously stolen from a London exhibition in 1966, recovered four days later by a dog named Pickles, then lost forever after Brazil was gifted permanent custody in 1970.",

    # Joke
    "{{JOKE_SETUP}}": "What do the Socceroos and a trades business have in common this time of year?",
    "{{JOKE_PUNCHLINE}}": "They're both trying to score before June 30 — and the rules say there's no overtime.",

    # Closing
    "{{CLOSING_QUOTE}}": "“In the depth of winter, I finally learned that within me there lay an invincible summer.”",
    "{{CLOSING_ATTR}}": "— Albert Camus",
    "{{CLOSING_MESSAGE}}": "It's a wet Friday in Carrum Downs — the last shower day before the weather eases into the weekend. Winter solstice is Sunday: the shortest day and longest night of the year. From here, the days start getting longer. Eleven days to EOFY — the Payday Super change is real and the payroll software check cannot wait much longer. And tonight, the Socceroos take on the USA at 5am AEST: gates open at Fed Square at 11pm if you want to watch it with thousands of other Australians, or set the alarm for 4:45am and watch from the couch. Either way — it's a big weekend. Go the Socceroos, Liall.",
}

with open("template.html", "r", encoding="utf-8") as f:
    html = f.read()

for placeholder, value in replacements.items():
    html = html.replace(placeholder, value)

remaining = re.findall(r"\{\{[A-Z_0-9]+\}\}", html)
if remaining:
    print(f"WARNING: Unreplaced placeholders: {remaining}")
else:
    print("All placeholders replaced successfully.")

with open("index.html", "w", encoding="utf-8") as f:
    f.write(html)

print("index.html written successfully.")
