#!/usr/bin/env python3
"""Read template.html, replace placeholders with today's content, write to index.html."""

import re

replacements = {
    "{{DATE}}": "Sunday, 23 August 2026",

    # Weather — Carrum Downs VIC, 5-day from Sun 23 Aug (BOM)
    "{{WEATHER_1}}": "SUN 23 · ⛅ Partly cloudy, slight chance of a shower · 6–18°C",
    "{{WEATHER_2}}": "MON 24 · ☁️ Cloudy, showers most likely evening · 6–18°C",
    "{{WEATHER_2_CLASS}}": "rain",
    "{{WEATHER_3}}": "TUE 25 · 🌧️ Cloudy, high chance of showers · 10–18°C",
    "{{WEATHER_3_CLASS}}": "rain",
    "{{WEATHER_4}}": "WED 26 · ☁️ Cloudy, showers most likely morning · 11–16°C",
    "{{WEATHER_5}}": "THU 27 · ⛅ Partly cloudy, showers most likely evening · 10–18°C",
    "{{WEATHER_ALERT}}": "No severe weather warnings are current for Melbourne metro or Carrum Downs. Tuesday is shaping up as the wettest day of the run, with shower risk again Monday evening and Wednesday morning — today, Sunday, is the best dry window this week for any exterior coating or blasting work.",

    # World
    "{{WORLD_1_FLAG}}": "🇻🇦 VATICAN · POPE'S FIRST VISIT TO SAN MARINO IN 15 YEARS",
    "{{WORLD_1_HEADLINE}}": "Pope Leo XIV Visits San Marino, Warns Against Power Placed Above Human Dignity",
    "{{WORLD_1_SUMMARY}}": "Pope Leo XIV made the first papal visit to the tiny republic of San Marino in over 15 years on Saturday, using the trip and a nearby Rimini gathering to warn against political and economic systems that put power above the individual. He's only the third pope ever to visit, after John Paul II in 1982 and Benedict XVI in 2011.",
    "{{WORLD_1_URL}}": "https://www.washingtonpost.com/world/2026/08/22/pope-leo-san-marino-abortion-politics-freedom-power/dc91f60c-9e0c-11f1-9cc4-2dc9b46e2d5c_story.html",

    "{{WORLD_2_FLAG}}": "🇲🇽 MEXICO · CATTLE TRADE REOPENS AFTER SCREWWORM SCARE",
    "{{WORLD_2_HEADLINE}}": "Mexico Resumes Cattle Exports to US After Year-Long Screwworm Ban",
    "{{WORLD_2_SUMMARY}}": "The US will reopen the Douglas, Arizona border crossing to Mexican cattle from Monday, ending a ban imposed over the flesh-eating New World screwworm parasite. Strict RFID tagging and staged daily quotas — starting at 700 head, rising to 900 — apply, a reminder that even livestock now travels with a full paper trail.",
    "{{WORLD_2_URL}}": "https://www.washingtonpost.com/business/2026/08/22/mexico-us-cattle-livestock-resume-imports-screwworm/554979be-9e10-11f1-9cc4-2dc9b46e2d5c_story.html",

    # Economics
    "{{ECON_1_FLAG}}": "🔋 ENERGY · BATTERIES SPIKE WHOLESALE POWER PRICES",
    "{{ECON_1_HEADLINE}}": "Mass Battery Charging Pushes WA Wholesale Power Prices Above $350/MWh",
    "{{ECON_1_SUMMARY}}": "Australia now ranks third globally for battery storage capacity, but in WA's grid, mass overnight battery charging is spiking wholesale spot prices to extreme highs as batteries compete for power in narrow windows. Worth remembering if you're weighing up a battery system as a guaranteed bill-cutter for the workshop — timing and grid conditions matter as much as the hardware.",
    "{{ECON_1_URL}}": "https://www.abc.net.au/news/2026-08-22/batteries-pushed-power-prices-up-in-midnight-charging-surge/107047470",

    "{{ECON_2_FLAG}}": "⛽ FUEL · PUMP PRICES CLIMB AGAIN",
    "{{ECON_2_HEADLINE}}": "National Petrol Average Rises to 204.1c/L as Wholesale Costs Jump",
    "{{ECON_2_SUMMARY}}": "The ACCC's latest weekly fuel monitoring shows the national unleaded average up 3.7c to 204.1c/L, driven by a 3% jump in wholesale import costs that typically flows through to bowsers over the next week or two. Diesel remains elevated following the fuel excise cut's expiry on 3 August — worth factoring into any quotes with a lot of driving between jobs.",

    # Tech / AI
    "{{TECH_1_FLAG}}": "🎵 AI TRANSPARENCY · APPLE MUSIC TO LABEL AI TRACKS",
    "{{TECH_1_HEADLINE}}": "Apple Music Will Require \"Made With AI\" Labels on AI-Generated Songs",
    "{{TECH_1_SUMMARY}}": "Apple has told record labels and distributors that any track with a \"material portion\" generated by AI must now be tagged, with visible labels rolling out to listeners later this year — a shift from the optional labelling it trialled in March. It's a preview of where disclosure rules are headed more broadly: if AI helps write a quote or a report you send a client, transparency about it may soon be less optional everywhere, not just in music.",
    "{{TECH_1_URL}}": "https://macdailynews.com/2026/08/21/apple-music-to-introduce-made-with-ai-labels-for-ai-generated-music-later-this-year/",

    "{{TECH_2_FLAG}}": "📦 LOGISTICS · AMAZON DRONES HEAD TO 500 CITIES",
    "{{TECH_2_HEADLINE}}": "Amazon Plans Sixfold Expansion of Prime Air Drone Delivery to Nearly 500 US Cities",
    "{{TECH_2_SUMMARY}}": "Amazon is scaling Prime Air from 11 sites to close to 500 US cities and towns by the end of the year, each covering about 175 square miles with 30–60 minute delivery windows. It's a reminder that \"last mile\" logistics is being reinvented fast — the same pressure that's pushing bigger players to rethink how parts and consumables reach a job site could reach small-business supply chains sooner than expected.",

    # Robotics
    "{{ROBOT_1_FLAG}}": "🤖 HUMANOID ROBOTS · 2,000+ ROBOTS COMPETE IN BEIJING",
    "{{ROBOT_1_HEADLINE}}": "Second World Humanoid Robot Games Opens in Beijing With Over 2,000 Robots",
    "{{ROBOT_1_SUMMARY}}": "More than 2,056 humanoid robots from 666 teams across 16 countries are competing in Beijing through 26 August — robot numbers have roughly doubled and team numbers are up 138% on last year's event. One training-session robot reportedly crashed hard enough to nearly break itself in half — a reminder that even the cutting edge of robotics still has its share of on-the-job stumbles, same as any apprentice's first week.",
    "{{ROBOT_1_URL}}": "https://news.cgtn.com/news/2026-08-21/Live-Second-World-Humanoid-Robot-Games-open-in-Beijing--1PNdFcjqPLO/p.html",

    # Australia
    "{{AUS_1_HEADLINE}}": "Third Woman Engages Lawyer Over Sydney Swans Hotel Scandal",
    "{{AUS_1_SUMMARY}}": "A third woman linked to an alleged incident at a Pullman Hotel in East Melbourne on 17 August has engaged Slater & Gordon to explore civil action, with five Swans players still suspended for the rest of the season.",
    "{{AUS_1_URL}}": "https://www.abc.net.au/news/2026-08-22/third-woman-legal-representation-civil-sydney-swans-scandal/107066742",

    "{{AUS_2_HEADLINE}}": "Australia on Track for Wettest El Niño Year on Record",
    "{{AUS_2_SUMMARY}}": "Despite the Bureau of Meteorology declaring a strong El Niño — usually a byword for drought — repeated rainbands have made 2026 unusually wet nationally, though forecasters expect the pattern to flip toward a hotter, drier spring and summer.",

    # Victoria
    "{{VIC_1_HEADLINE}}": "Victorian Government Pledges $230m for 10 Free Walk-In Dental Clinics",
    "{{VIC_1_SUMMARY}}": "Premier Ben Carroll announced the funding at Labor's \"100 Days Out\" rally ahead of the November state election — seven clinics for metro Melbourne, three regional, aiming to treat over 100,000 patients a year once the first sites open in mid-2027.",

    # Science
    "{{SCI_1_FLAG}}": "🦷 MEDICINE · YOUR TEETH MAY PREDICT SURGERY OUTCOMES",
    "{{SCI_1_HEADLINE}}": "Tooth Count Linked to Survival After Pancreatic Cancer Surgery, Study Finds",
    "{{SCI_1_SUMMARY}}": "In a study of 339 patients, those with 21 or more natural teeth survived a median of roughly 60 months after pancreatic surgery, compared with about 39 months for those with fewer — researchers think tooth loss tracks decades of inflammation and frailty rather than causing the outcome directly. A genuinely odd but well-evidenced reminder that the basics — including a dental check-up — aren't unrelated to how well your body handles a big medical event.",

    # Business insight
    "{{INSIGHT_TITLE}}": "The ATO Already Knows What You Paid Your Subbies",
    "{{INSIGHT_BODY}}": "The Taxable Payments Annual Report deadline lands this Friday, 28 August, and this year the Tax Office is matching around $21 billion in reported contractor payments straight against what those contractors declared on their own returns — no human needed to flag a mismatch. If you pay subcontractors, a typo or a missing invoice on your side is exactly the kind of thing that now surfaces automatically. The fix isn't dodging the report, it's using the AI-assisted reconciliation most modern accounting software (Xero, MYOB) already has — five minutes cross-checking contractor payments against invoices before you lodge beats a please-explain letter in October.",

    # Fun facts
    "{{FACT_1}}": "Isaac Asimov coined the word \"robotics\" in his 1941 short story Liar! — he later admitted he assumed the word already existed, genuinely surprised to learn he'd invented an entirely new term rather than borrowed one.",
    "{{FACT_2}}": "A newly described \"supergiant\" isopod, Bathynomus vaderi, found off Vietnam's coast, grows over 30cm long and was named for its Darth Vader–helmet-shaped head — locals had been eating it as seafood for years before scientists realised it was a new species.",
    "{{FACT_3}}": "Global robot density in manufacturing hit 162 robots for every 10,000 workers in 2023, with automation leaders South Korea and Japan both topping 400 — roughly one robot for every 25 factory workers in those countries.",

    # Joke
    "{{JOKE_SETUP}}": "What do you call a welder who never shows up to the job?",
    "{{JOKE_PUNCHLINE}}": "A ne'er-do-weld.",

    # Closing
    "{{CLOSING_QUOTE}}": "\"The only way to make sense out of change is to plunge into it, move with it, and join the dance.\"",
    "{{CLOSING_ATTR}}": "— Alan Watts",
    "{{CLOSING_MESSAGE}}": "Today's your best dry window of the week in Carrum Downs before showers build back in from Monday evening through Tuesday, so it's a decent Sunday to get any outdoor coating work sorted while the going's good. With the ATO's contractor-payment deadline five days out and battery-driven power price swings back in the news, it's also a fair prompt to spend ten quiet minutes on the books before the week gets away from you.",
}

with open("template.html", "r", encoding="utf-8") as f:
    html = f.read()

for placeholder, value in replacements.items():
    html = html.replace(placeholder, value)

remaining = re.findall(r"\{\{[A-Z_0-9]+\}\}", html)
if remaining:
    print(f"WARNING: Unreplaced placeholders: {remaining}")
else:
    print("All placeholders replaced successfully.")

with open("index.html", "w", encoding="utf-8") as f:
    f.write(html)

print("index.html written successfully.")
